# https://taskfile.dev

version: '3'

env:
  GOPATH:
    sh: go env GOPATH
  TZ: UTC

tasks:
  lint:install:
    status:
      - test -f $GOPATH/bin/golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  lint:
    deps:
      - lint:install
    cmds:
      - golangci-lint run

  test:install:
    status:
      - go version
      - test -f $GOPATH/bin/gotestsum
    cmds:
      - go install gotest.tools/gotestsum@latest
  test:
    deps:
      - test:install
    cmds:
      - gotestsum --junitfile=unit-tests.xml -- -timeout 30s -race -count=1 ./...
